# Generated by Django 2.2 on 2020-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentID', models.CharField(max_length=20)),
                ('equipmentDesc', models.TextField()),
                ('building', models.CharField(blank=True, max_length=350, null=True)),
                ('elevation', models.IntegerField()),
                ('roomID', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
