# Generated by Django 2.2 on 2020-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddata',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='equipmentDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
