# Generated by Django 2.2 on 2020-02-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0004_auto_20200214_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddata',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
